### ISSUE TITLE
Problem installing library on OSX: multiple errors with Exception.h and Exception.cpp

### ISSUE THREAD

**Issue by changlongzj** [api-ai/libapiai#1]
I am trying to install the C++ library on OS X but I am getting multiple errors with Exception.h/cpp, such as:
- expected ';' at end of declaration list: `Exception(const char *reason) _GLIBCXX_USE_NOEXCEPT;`
- exception specification of overriding function is more lax than base version `virtual const char* what() const _GLIBCXX_USE_NOEXCEPT override;`
- ...

Is a problem with my CMake, compiler... ?

Thanks!

**Comment by artemgoncharuk** [comment]
Hi @changlongzj ,

We recommend using the iOS SDK (the name is a misnomer, it works on MacOS as well) - https://github.com/api-ai/api-ai-ios-sdk

Thanks,
Art
